version: '3'

services:
  redis:
    image: redis
    # restart: unless-stopped
    # tty: true
    ports:
      - 6379:6379
    container_name: redis-container

networks:
  default:
    external:
      name: nginx-proxy
